apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: battleship
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: battleship-nodejs
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      ref:
        branch: master
      url: https://github.com/Eknathreddy09/battleships-nodejs.git
